import { Container } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import CardTwo from '../components/cardDesign/CardTwo'
import Carousel from '../components/carousel/Carousel'
import India from '../components/india/India'
import Latest from '../components/Latest/Latest'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container sx={{background:'white'}}>
           <Carousel/>
        </Container>
        <Container className={styles.latestContainer}>
          <Latest/>
        </Container>
        <Container sx={{width:'100%',background:'white',paddingBottom:'20px'}} >
          <India/>
        </Container>
       </main>
    </div>
  )
}
